import DataLineDataLine9service_spec_characteristicEController from '../data-line-data-line9-service-spec-characteristic-e';

var DataLineDataLine9service_spec_characteristicENewController = DataLineDataLine9service_spec_characteristicEController;
export default DataLineDataLine9service_spec_characteristicENewController;
